### ISSUE TITLE
Self suicide not caught

### ISSUE THREAD

**Issue by m0ose** [MichalPaszkiewicz/go#46]
It doesn't seem to stop you from committing suicide.

![screen shot 2015-06-17 at 9 40 01 am](https://cloud.githubusercontent.com/assets/393666/8211649/e648f948-14d4-11e5-8506-2f2ef1bcaaec.png)

**Comment by MichalPaszkiewicz** [comment]
Thank you for raising this issue!

I have not worked on this project for a long time, and it will need quite some refactoring, but I will try to get to this as soon as possible. 

If you find a solution before then, I will happily accept any (good) pull requests :)

Thanks again,

Michal

**Comment by MichalPaszkiewicz** [comment]
This issue is now fixed!

**Comment by m0ose** [comment]
cool

Cody Smith
